# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23157ce994433bf3354806f30996762728680ad0749dfc0d953427ecb2dc5a7ef4156d83b3e6181f4aeca62a8ae15b963a707c71e2b5022d4cf0ef66c36e7692

test:
  secret_key_base: 0f015145769b08ba23bdb926afb9e33e89f5f2fbb375d5fdcc8eecc86a94e29a33d0ae0c38bd93a62c06028b29ea0cb2e2cc457749533cdd63dc2c6846650c12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
